one_hot_translate = {
    ('DefReb', '-1', 'DefReb', '-1'): 'DefReb',
    ('Sub', '-1', '-1', '-1'): 'Sub',
    ('JS', '-1', 'miss3', '0'): 'miss3',
    ('FreeThrow', '-1', 'make1', '1'): 'makeF',
    ('OffReb', '-1', 'OffReb', '-1'): 'OffReb',
    ('JS', '-1', 'miss2', '0'): 'miss2',
    ('ShootingFoul', 'DrawnBy', 'ShootingFoul', '-1'): 'SFoul',
    ('JS', 'assist', 'make3', '3'): 'make3',
    ('LU', '-1', 'miss2', '0'): 'miss2',
    ('LU', '-1', 'make2', '2'): 'make2',
    ('PersonalFoul', 'DrawnBy', 'PersonalFoul', '-1'): 'PFoul',
    ('JS', '-1', 'make2', '2'): 'make2',
    ('Timeout', '-1', '-1', '-1'): 'timeout',
    ('LU', 'assist', 'make2', '2'): 'make2',
    ('FreeThrow', '-1', 'make1', '0'): 'missF',
    ('JS', 'assist', 'make2', '2'): 'make2',
    ('bad pass', 'steal', 'turnover', '-1'): 'turnover',
    ('DK', 'assist', 'make2', '2'): 'make2',
    ('LU', 'block', 'miss2', '0'): 'miss2',
    ('lost ball', 'steal', 'turnover', '-1'): 'turnover',
    ('OffensiveFoul', '-1', 'turnover', '-1'): 'OFoul',
    ('BadPass', 'steal', 'turnover', '-1'): 'turnover',
    ('BadPass', '-1', 'turnover', '-1'): 'turnover',
    ('JS', '-1', 'make3', '3'): 'make3',
    ('HS', '-1', 'miss2', '0'): 'miss2',
    ('JS', 'block', 'miss2', '0'): 'miss2',
    ('OffensiveFoul', 'DrawnBy', 'OffensiveFoul', '-1'): 'OFoul',
    ('LooseBallFoul', 'DrawnBy', 'LooseBallFoul', '-1'): 'PFoul',
    ('LostBall', 'steal', 'turnover', '-1'): 'turnover',
    ('DK', '-1', 'make2', '2'): 'make2',
    ('Traveling', '-1', 'turnover', '-1'): 'turnover',
    ('HS', '-1', 'make2', '2'): 'make2',
    ('HS', 'assist', 'make2', '2'): 'make2',
    ('ShotClockViolation', '-1', 'turnover', '-1'): 'turnover',
    ('PersonalTakeFoul', 'DrawnBy', 'PersonalTakeFoul', '-1'): 'PFoul',
    ('LostBall', '-1', 'turnover', '-1'): 'turnover',
    ('KickBallViolation', '-1', 'KickBallViolation', '-1'): 'violation',
    ('TechnicalFoul', '-1', 'TechnicalFoul', '-1'): 'TFoul',
    ('PersonalFoul', '-1', '-1', '-1'): 'PFoul',
    ('ChargeFoul', 'DrawnBy', 'ChargeFoul', '-1'): 'CFoul',
    ('OutOfBoundsLB', '-1', 'turnover', '-1'): 'turnover',
    ('OutOfBounds', '-1', 'turnover', '-1'): 'turnover',
    ('DK', '-1', 'miss2', '0'): 'miss2',
    ('ShootingBlockFoul', 'DrawnBy', 'ShootingBlockingFoul', '-1'): 'SFoul',
    ('DefGoaltending', '-1', 'DefGoaltending', '-1'): 'DGoalTend',
    ('JS', 'block', 'miss3', '0'): 'miss3',
    ('D3SecTech', '-1', '-1', '-1'): 'D3Sec',
    ('PersonalBlockFoul', 'DrawnBy', 'PersonalBlockingFoul', '-1'): 'PFoul',
    ('TI', '-1', 'miss2', '0'): 'miss2',
    ('DK', 'block', 'miss2', '0'): 'miss2',
    ('TI', '-1', 'make2', '2'): 'make2',
    ('3sec', '-1', 'turnover', '-1'): 'O3sec',
    ('DelayOfGame', '-1', 'DelayOfGame', '-1'): 'DOG',
    ('InstantReplay', '-1', 'RulingStands', '-1'): 'IRRS',
    ('HS', 'block', 'miss2', '0'): 'miss2',
    ('Turnover', '-1', 'turnover', '-1'): 'turnover',
    ('LooseBallFoul', '-1', 'LooseBallFoul', '-1'): 'PFoul',
    ('BackCourtTurnover', '-1', 'turnover', '-1'): 'turnover',
    ('OffGoaltending', '-1', 'turnover', '-1'): 'OGoalTend',
    ('JumpBallViolation', '-1', 'JumpBallViolation', '-1'): 'violation',
    ('PersonalTakeFoul', '-1', 'PersonalTakeFoul', '-1'): 'PFoul',
    ('AFPFoul', 'DrawnBy', 'AFPFoul', '-1'): 'AFPFoul',
    ('DiscontinueDribbleTurnover', '-1', 'turnover', '-1'): 'turnover',
    ('Palming', '-1', 'turnover', '-1'): 'turnover',
    ('DblDribble', '-1', 'turnover', '-1'): 'turnover',
    ('FlagrantFoul1', 'DrawnBy', 'FlagrantFoul1', '-1'): 'F1Foul',
    ('ClearPathFoul', '-1', 'ClearPathFoul', '-1'): 'CPFoul',
    ('LaneViolation', '-1', 'LaneViolation', '-1'): 'violation',
    ('PersonalBlockFoul', '-1', '-1', '-1'): 'PFoul',
    ('turnover', 'steal', 'turnover', '-1'): 'turnover',
    ('Ejection', '-1', 'Ejection', '-1'): 'ejection',
    ('InboundFoul', '-1', 'InboundFoul', '-1'): 'PFoul',
    ('inboundTurnover', '-1', 'turnover', '-1'): 'turnover',
    ('LaneViolation', '-1', 'turnover', '-1'): 'turnover',
    ('Turnover5Second', '-1', 'turnover', '-1'): 'turnover',
    ('KickedBallTurnover', '-1', 'turnover', '-1'): 'turnover',
    ('5 sec', '-1', 'turnover', '-1'): 'turnover',
    ('TechnicalFoul', '-1', '-1', '-1'): 'TFoul',
    ('IllegalScreen', '-1', 'turnover', '-1'): 'turnover',
    ('8 sec', '-1', 'turnover', '-1'): 'turnover',
    ('FlagrantFoul1', '-1', '-1', '-1'): 'F1Foul',
    ('OffensiveFoul', '-1', '-1', '-1'): 'OFoul',
    ('IllegalAssist', '-1', 'turnover', '-1'): 'turnover',
    ('TI', 'block', 'miss2', '0'): 'miss2',
    ('AFPFoul', '-1', 'AFPFoul', '-1'): 'AFPFoul',
    ('JumpBallViolation', '-1', 'turnover', '-1'): 'violation',
    ('5sec', '-1', 'turnover', '-1'): 'turnover',
    ('ChargeFoul', '-1', '-1', '-1'): 'CFoul',
    ('ShootingFoul', '-1', '-1', '-1'): 'SFoul',
    ('FlagrantFoul2', 'DrawnBy', 'FlagrantFoul2', '-1'): 'F2Foul',
    ('HS', '-1', 'miss3', '0'): 'miss3',
    ('ShootingBlockFoul', '-1', '-1', '-1'): 'SFoul',
    ('LU', '-1', 'miss3', '0'): 'miss3',
    ('LU', 'block', 'miss3', '0'): 'miss3',
    ('DoublePersonal', '-1', 'turnover', '-1'): 'turnover',
    ('SwingingElbows', '-1', 'turnover', '-1'): 'turnover',
    ('PunchedBall', '-1', 'turnover', '-1'): 'turnover',
    ('HS', 'block', 'miss3', '0'): 'miss3',
    ('TI', 'block', 'miss3', '0'): 'miss3',
    ('HS', 'assist', 'make3', '3'): 'make3',
    ('LU', '-1', 'make3', '3'): 'make3',
    ('HS', '-1', 'make3', '3'): 'make3',
    ('turnover', '-1', 'turnover', '-1'): 'turnover',
    ('InstantReplay', '-1', 'Unknown', '-1'): 'timeout',
    ('Violation', '-1', 'Violation', '-1'): 'violation'
}

print(set(list(one_hot_translate.values())))
print(len(set(list(one_hot_translate.values()))))

embed_dict = {'<PAD>': 0,
              '<START>': 1,
              '<END>': 2}
count = 3
for words in set(list(one_hot_translate.values())):
    embed_dict[words] = count
    count += 1

print(embed_dict)


